---
# vars file for osp.servers
osp_servers:
- name: frontend
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: frontend
  network: int_network
  floating_ip_network: ext_network
  meta:
    { group: frontends, deployment_name: QA}

- name: app1
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: apps
  network: int_network
  floating_ip_network: ext_network
  meta:
    { group: apps, deployment_name: QA}

- name: app2
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: apps
  network: int_network
  floating_ip_network: ext_network
  meta:
    { group: apps, deployment_name: QA}

- name: db
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: db
  network: int_network
  floating_ip_network: ext_network
  meta:
    { group: appdbs, deployment_name: QA}