---
# tasks file for db-tier

# install latest postgres on db server
- name: install progress
  yum:
    name: postgresql-server
    state: latest

# initialize postgres
- name: initilize postgres
  command: postgresql-setup initdb
  register: r_postgres_initdb
  failed_when:
  - r_postgres_initdb.rc != 0
  - r_postgres_initdb.stdout != 'Data directory is not empty!'
  changed_when:
  - r_postgres_initdb.rc == 0

# start and enable postgres on boot
- name: start and enable postgresql
  service:
    name: postgresql
    state: started
    enabled: yes